create extension if not exists pgcrypto;

create table if not exists public.video_shop_videos (
  id uuid primary key default gen_random_uuid(),
  merchant_id bigint not null,
  title text not null,
  badge text,
  tiktok_url text not null,
  tiktok_video_id text not null,
  thumbnail_url text,
  description text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists video_shop_videos_merchant_tiktok_uidx
  on public.video_shop_videos (merchant_id, tiktok_video_id);

create index if not exists video_shop_videos_feed_idx
  on public.video_shop_videos (merchant_id, is_active, sort_order);

create table if not exists public.video_shop_video_products (
  id uuid primary key default gen_random_uuid(),
  video_id uuid not null references public.video_shop_videos(id) on delete cascade,
  external_product_id bigint not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique(video_id, external_product_id)
);

create index if not exists video_shop_video_products_video_idx
  on public.video_shop_video_products(video_id, sort_order);

create table if not exists public.video_shop_events (
  id bigint generated by default as identity primary key,
  merchant_id bigint not null,
  video_id uuid references public.video_shop_videos(id) on delete set null,
  external_product_id bigint,
  event_type text not null check (
    event_type in ('impression','open','next','prev','product_click')
  ),
  session_id text,
  page_url text,
  user_agent text,
  created_at timestamptz not null default now()
);

create index if not exists video_shop_events_analytics_idx
  on public.video_shop_events(merchant_id, created_at desc, event_type);

create or replace function public.set_video_shop_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_video_shop_videos_updated_at on public.video_shop_videos;
create trigger trg_video_shop_videos_updated_at
before update on public.video_shop_videos
for each row execute function public.set_video_shop_updated_at();

alter table public.video_shop_videos enable row level security;
alter table public.video_shop_video_products enable row level security;
alter table public.video_shop_events enable row level security;

-- Seed current videos for Link Store (merchant id confirmed: 1829345766)
insert into public.video_shop_videos
  (merchant_id, title, badge, tiktok_url, tiktok_video_id, description, sort_order, is_active)
values
  (1829345766, 'كفر دريب لنك – 17 برو ماكس | MagSafe', '🔥 الأكثر طلبًا',
   'https://www.tiktok.com/@link.60/video/7676879558678711572',
   '7676879558678711572',
   'شوف الكفر بالفيديو، وبعدها اختر اللون المناسب وأكمل طلبك مباشرة.',
   1, true),
  (1829345766, 'كفر دريب لنك – 17 برو | MagSafe', '✨ Link Drip',
   'https://www.tiktok.com/@link.60/video/7679874195882265877',
   '7679874195882265877',
   'شوف المنتج على الطبيعة قبل الشراء، واختر اللون المناسب من صفحة المنتج.',
   2, true),
  (1829345766, 'شوف منتجات Link قبل ما تختار', '🎥 منتجات Link بالفيديو',
   'https://www.tiktok.com/@link.60/video/7680643557203528980',
   '7680643557203528980',
   'المنتجات الظاهرة بالفيديو متاحة من Link Store. اختر المنتج المناسب لجهازك.',
   3, true)
on conflict (merchant_id, tiktok_video_id)
do update set
  title = excluded.title,
  badge = excluded.badge,
  tiktok_url = excluded.tiktok_url,
  description = excluded.description,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  updated_at = now();

insert into public.video_shop_video_products(video_id, external_product_id, sort_order)
select id, 1335345819, 1
from public.video_shop_videos
where merchant_id=1829345766 and tiktok_video_id='7676879558678711572'
on conflict do nothing;

insert into public.video_shop_video_products(video_id, external_product_id, sort_order)
select id, 101121129, 1
from public.video_shop_videos
where merchant_id=1829345766 and tiktok_video_id='7679874195882265877'
on conflict do nothing;

insert into public.video_shop_video_products(video_id, external_product_id, sort_order)
select v.id, x.product_id, x.sort_order
from public.video_shop_videos v
cross join (values (1335345819::bigint,1),(101121129::bigint,2)) x(product_id,sort_order)
where v.merchant_id=1829345766 and v.tiktok_video_id='7680643557203528980'
on conflict do nothing;
