const {test,afterEach}=require('node:test');const assert=require('node:assert/strict');const {PGlite}=require('@electric-sql/pglite');const fs=require('node:fs');
process.env.SUPABASE_URL='https://test.supabase.co';process.env.SUPABASE_SERVICE_ROLE_KEY='private-db-key';process.env.VIDEO_SHOP_ADMIN_TOKEN='old-admin';process.env.CRM_AUTH_MODE='supabase';
const auth=require('../lib/admin-auth'),handler=require('../api/crm-admin');const original=global.fetch;afterEach(()=>{global.fetch=original;process.env.CRM_AUTH_MODE='supabase';});
const id='11111111-1111-4111-8111-111111111111',user={id,email:'admin@example.com',user_metadata:{role:'admin'}};const json=(data,status=200)=>new Response(JSON.stringify(data),{status});const response=()=>({headers:{},setHeader(k,v){this.headers[k]=v;},end(body){this.body=JSON.parse(body);}});
const req=(method='GET',cookie='link_crm_access=access')=>({method,headers:{cookie,origin:'https://link-video-shop.vercel.app'}});
function stub(allowed=true){global.fetch=async(url,opts)=>{const u=new URL(url);assert.equal(u.origin,'https://test.supabase.co');if(u.pathname.endsWith('/user'))return opts.headers.Authorization==='Bearer access'?json(user):json({},401);if(u.pathname.includes('/rest/v1/crm_admin_members')){assert.ok(u.searchParams.get('merchant_id')==='eq.1829345766');assert.equal(u.searchParams.get('user_id'),'eq.'+id);return json(allowed?[{role:'admin'}]:[]);}if(u.pathname.endsWith('/token'))return json({access_token:'access',refresh_token:'refresh-private',expires_in:3600,user});if(u.pathname.endsWith('/logout'))return json({});throw Error('unexpected request');};}
test('Supabase auth rejects old admin token and forged cookie; only active merchant members are authorized',async()=>{stub();await assert.rejects(auth.requireAdmin({method:'GET',headers:{authorization:'Bearer old-admin'}}),e=>e.statusCode===401);assert.equal((await auth.requireAdmin(req())).id,id);stub(false);await assert.rejects(auth.requireAdmin(req()),e=>e.statusCode===403);});
test('login verifies membership and keeps all tokens in Secure HttpOnly cookies',async()=>{stub();const r=response();await handler({method:'POST',query:{resource:'auth',action:'login'},headers:{origin:'https://link-video-shop.vercel.app'},body:{email:user.email,password:'private-password'}},r);assert.equal(r.statusCode,200);assert.equal(r.body.user.email,user.email);assert.ok(!JSON.stringify(r.body).includes('refresh-private'));assert.ok(r.headers['Set-Cookie'].every(c=>c.includes('Secure')&&c.includes('HttpOnly')&&c.includes('SameSite=Lax')));stub(false);const denied=response();await handler({method:'POST',query:{resource:'auth',action:'login'},headers:{origin:'https://link-video-shop.vercel.app'},body:{email:user.email,password:'private-password'}},denied);assert.equal(denied.statusCode,403);assert.equal(denied.headers['Set-Cookie'],undefined);});
test('cookie-authenticated mutations and login enforce production origin before IO; bad mode fails closed',async()=>{global.fetch=()=>{throw Error('unexpected IO');};await assert.rejects(auth.requireAdmin({method:'PUT',headers:{cookie:'link_crm_access=access',origin:'https://evil.test'}}),e=>e.statusCode===403);await assert.rejects(auth.login({headers:{origin:'https://evil.test'}},response(),{email:user.email,password:'password'}),e=>e.statusCode===403);process.env.CRM_AUTH_MODE='typo';await assert.rejects(auth.requireAdmin(req()),e=>e.statusCode===503);});
test('expired session refresh rotates cookies and rechecks permission; logout expires both cookies',async()=>{stub();const r=response();assert.equal((await auth.session(req('GET','link_crm_access=expired; link_crm_refresh=refresh-private'),r)).id,id);assert.ok(r.headers['Set-Cookie'][0].startsWith('link_crm_access=access'));const out=response();await auth.logout(req(),out);assert.ok(out.headers['Set-Cookie'].every(c=>c.includes('Max-Age=0')));});
test('auth SQL is repeatable and membership cannot be self-assigned through public roles',async()=>{const db=new PGlite();try{await db.exec('create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key);');const sql=fs.readFileSync('crm-auth.sql','utf8');await db.exec(sql);await db.exec(sql);for(const role of ['anon','authenticated'])for(const privilege of ['SELECT','INSERT','UPDATE','DELETE'])assert.equal((await db.query(`select has_table_privilege('${role}','crm_admin_members','${privilege}') allowed`)).rows[0].allowed,false);assert.equal((await db.query("select relrowsecurity from pg_class where relname='crm_admin_members'")).rows[0].relrowsecurity,true);}finally{await db.close();}});
