const {test,afterEach}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const {PGlite}=require('@electric-sql/pglite');
process.env.SUPABASE_URL='https://test.supabase.co';process.env.SUPABASE_SERVICE_ROLE_KEY='private';process.env.VIDEO_SHOP_ADMIN_TOKEN='admin';
const wa=require('../lib/whatsapp-workspace'),handler=require('../api/crm-admin');const original=global.fetch;afterEach(()=>global.fetch=original);
function res(){return {setHeader(){},end(body){this.body=JSON.parse(body);}};}
test('WhatsApp drafts schema is repeatable, private, and cannot enter live mode',async()=>{const db=new PGlite();try{await db.exec('create role anon;create role authenticated;create role service_role bypassrls;');const sql=fs.readFileSync('crm-whatsapp.sql','utf8');await db.exec(sql);await db.exec(sql);assert.equal((await db.query("select relrowsecurity from pg_class where relname='crm_whatsapp_workspace'")).rows[0].relrowsecurity,true);for(const role of ['anon','authenticated']){for(const privilege of ['SELECT','INSERT','UPDATE','DELETE'])assert.equal((await db.query(`select has_table_privilege('${role}','crm_whatsapp_workspace','${privilege}') allowed`)).rows[0].allowed,false);}await db.exec("set role service_role;insert into crm_whatsapp_workspace(merchant_id,configuration) values (1829345766,'{}');");assert.equal((await db.query('select count(*)::int n from crm_whatsapp_workspace')).rows[0].n,1);await assert.rejects(db.exec("update crm_whatsapp_workspace set mode='live'"));}finally{await db.close();}});
test('WhatsApp settings reject invalid phone, duplicates and unsupported substitutions; secrets and live flags are dropped',()=>{const d=wa.defaults();assert.deepEqual(wa.validate({...d,phone:'+966500000000',mode:'live',access_token:'do-not-store'}),{...d,phone:'+966500000000'});for(const change of [{phone:'0500000000'},{provider:'other'},{tags:['x','x']},{cart_delay:0},{templates:[{id:'cart',body:'{{access_token}}'},...d.templates.slice(1)]}])assert.throws(()=>wa.validate({...d,...change}));});
test('WhatsApp admin auth precedes storage; missing schema is explicit; save is merchant scoped and sends no messages',async()=>{global.fetch=()=>{throw Error('unexpected IO');};let r=res();await handler({method:'GET',query:{resource:'whatsapp'},headers:{authorization:'wrong'}},r);assert.equal(r.statusCode,401);
global.fetch=async()=>new Response(JSON.stringify({code:'PGRST205'}),{status:404});const missing=await wa.load();assert.equal(missing.storage_ready,false);assert.equal(missing.mode,'draft');
let writes=0;global.fetch=async(url,opts)=>{assert.ok(String(url).startsWith('https://test.supabase.co/rest/v1/crm_whatsapp_workspace'));assert.equal(opts.method,'POST');const body=JSON.parse(opts.body);assert.equal(body.merchant_id,1829345766);assert.equal(body.mode,'draft');assert.ok(!('access_token' in body.configuration));writes++;return new Response(null,{status:201});};await wa.save({...wa.defaults(),mode:'live',access_token:'secret'});assert.equal(writes,1);
});
