const {chromium}=require("playwright");
const fs=require("fs");
const url="https://link-video-shop-git-protection-3d-prototype-anasmhdy1994-3118.vercel.app/protection-lab/";
(async()=>{
  const browser=await chromium.launch({headless:true,args:["--use-gl=angle","--use-angle=swiftshader"]});
  const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1});
  const errors=[];
  page.on("pageerror",e=>errors.push(e.message));
  page.on("console",m=>{if(m.type()==="error")errors.push(m.text())});
  await page.goto(url,{waitUntil:"networkidle",timeout:60000});
  await page.locator("#loading.hidden").waitFor({timeout:30000});
  fs.mkdirSync("prototype/web/screenshots",{recursive:true});
  await page.screenshot({path:"prototype/web/screenshots/before.png",fullPage:true});
  await page.locator("#case-toggle").click();
  await page.waitForTimeout(1800);
  await page.screenshot({path:"prototype/web/screenshots/after.png",fullPage:true});
  const result={url,title:await page.title(),selected:await page.locator("#case-toggle").getAttribute("aria-pressed"),count:await page.locator("#count").textContent(),canvas:await page.locator("#scene canvas").count(),errors};
  fs.writeFileSync("prototype/web/screenshots/verification.json",JSON.stringify(result,null,2));
  console.log(result);
  await browser.close();
  if(result.selected!=="true"||result.count!=="2"||errors.length)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1});
