const {sb,MERCHANT_ID}=require('./supabase');
const crypto=require('node:crypto');
const mode=()=>{const value=process.env.CRM_AUTH_MODE||'legacy';if(!['legacy','supabase'].includes(value))throw fail(503,'إعداد وضع الدخول غير صالح');return value;};
function fail(statusCode,message){return Object.assign(new Error(message),{statusCode});}
function origin(){const value=process.env.CRM_APP_ORIGIN||'https://link-video-shop.vercel.app';const url=new URL(value);if(url.origin!==value||(process.env.NODE_ENV==='production'&&url.protocol!=='https:'))throw fail(503,'إعداد عنوان التطبيق غير صالح');return value;}
function checkOrigin(req){if(req.headers.origin!==origin())throw fail(403,'ابدأ الطلب من لوحة لنك');}
function cookies(req){const result={};for(const part of String(req.headers.cookie||'').split(';')){const index=part.indexOf('=');if(index>0){const key=part.slice(0,index).trim();if(Object.hasOwn(result,key))throw fail(401,'انتهت الجلسة');try{result[key]=decodeURIComponent(part.slice(index+1));}catch{throw fail(401,'انتهت الجلسة');}}}return result;}
function setSession(res,data){if(!data?.access_token||!data?.refresh_token)throw fail(503,'تعذر تجهيز الجلسة');const secure=new URL(origin()).protocol==='https:'?'; Secure':'';const maxAge=data.expires_in?Math.max(60,Math.min(86400,Number(data.expires_in))):3600;res.setHeader('Set-Cookie',[`link_crm_access=${encodeURIComponent(data.access_token)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${maxAge}${secure}`,`link_crm_refresh=${encodeURIComponent(data.refresh_token)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=604800${secure}`]);}
function clearSession(res){const secure=new URL(origin()).protocol==='https:'?'; Secure':'';res.setHeader('Set-Cookie',['link_crm_access','link_crm_refresh'].map(name=>`${name}=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0${secure}`));}
async function auth(path,options={}){const base=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!base||!key)throw fail(503,'إعدادات تسجيل الدخول غير مكتملة');let response;try{response=await fetch(`${base}/auth/v1/${path}`,{...options,headers:{apikey:key,'Content-Type':'application/json',...options.headers},signal:AbortSignal.timeout(12000),redirect:'error'});}catch{throw fail(503,'تعذر الاتصال بخدمة الدخول');}const data=await response.json().catch(()=>({}));if(!response.ok){if(response.status===429)throw fail(429,'محاولات كثيرة؛ انتظر قليلاً ثم أعد المحاولة');if(response.status>=500)throw fail(503,'خدمة تسجيل الدخول غير متاحة مؤقتاً');throw fail(401,'البريد أو كلمة المرور غير صحيحة، أو انتهت الجلسة');}return data;}
async function member(user){if(!user?.id||! /^[a-f0-9-]{36}$/i.test(user.id))throw fail(401,'انتهت الجلسة');let rows;try{rows=await sb(`crm_admin_members?merchant_id=eq.${MERCHANT_ID}&user_id=eq.${user.id}&active=eq.true&select=role&limit=1`,{signal:AbortSignal.timeout(12000)});}catch{throw fail(503,'شغّل crm-auth.sql وأكمل صلاحية الحساب في سوبابيس');}if(rows?.[0]?.role!=='admin')throw fail(403,'هذا الحساب لا يملك صلاحية إدارة متجر لنك');return {id:user.id,email:user.email||'',role:'admin'};}
async function verified(access){if(!access)throw fail(401,'سجّل الدخول أولاً');const user=await auth('user',{headers:{Authorization:`Bearer ${access}`}});return member(user);}
async function requireAdmin(req){
 if(mode()==='legacy'){const expected=process.env.VIDEO_SHOP_ADMIN_TOKEN;if(!expected)throw fail(503,'إعدادات تسجيل الدخول غير مكتملة');const header=String(req.headers.authorization||'');const actual=header.startsWith('Bearer ')?header.slice(7):'';const a=Buffer.from(actual),b=Buffer.from(expected);if(a.length!==b.length||!crypto.timingSafeEqual(a,b))throw fail(401,'Unauthorized');return {role:'legacy_admin'};}
 const bearer=String(req.headers.authorization||'').startsWith('Bearer ')?req.headers.authorization.slice(7):'';
 const access=cookies(req).link_crm_access||bearer;
 if(cookies(req).link_crm_access&&!['GET','HEAD','OPTIONS'].includes(req.method))checkOrigin(req);
 req.adminUser=await verified(access);return req.adminUser;
}
async function session(req,res){const c=cookies(req);try{return await verified(c.link_crm_access);}catch(e){if(e.statusCode!==401)throw e;if(!c.link_crm_refresh)throw e;const data=await auth('token?grant_type=refresh_token',{method:'POST',body:JSON.stringify({refresh_token:c.link_crm_refresh})});const user=await member(data.user);setSession(res,data);return user;}}
async function login(req,res,body){checkOrigin(req);if(typeof body.email!=='string'||body.email.length>254||!/^\S+@\S+\.\S+$/.test(body.email)||typeof body.password!=='string'||!body.password||body.password.length>1024)throw fail(400,'أدخل البريد الإلكتروني وكلمة المرور');const data=await auth('token?grant_type=password',{method:'POST',body:JSON.stringify({email:body.email.trim(),password:body.password})});const user=await member(data.user);setSession(res,data);return user;}
async function logout(req,res){checkOrigin(req);const c=cookies(req);clearSession(res);let access=c.link_crm_access;if(access){try{await auth('logout?scope=local',{method:'POST',headers:{Authorization:`Bearer ${access}`}});return;}catch(e){if(e.statusCode!==401)throw e;}}if(c.link_crm_refresh){try{const data=await auth('token?grant_type=refresh_token',{method:'POST',body:JSON.stringify({refresh_token:c.link_crm_refresh})});await auth('logout?scope=local',{method:'POST',headers:{Authorization:`Bearer ${data.access_token}`}});}catch(e){if(e.statusCode!==401)throw e;}}}
module.exports={mode,requireAdmin,login,logout,session,clearSession};
