const {sb,fail,MERCHANT_ID,json,bodyObject}=require('./crm');
const ID=/^[0-9]{1,20}$/, UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const TAGS=new Set(['case','screen','lens','camera_frame','charger','cable','other']);
function text(v,max){if(typeof v!=='string'||!v.trim()||v.trim().length>max)throw fail(400,'أكمل الحقول المطلوبة');return v.trim();}
function key(product,variant=''){if(typeof product!=='string'||!ID.test(product)||typeof variant!=='string'||(variant&&!ID.test(variant)))throw fail(400,'معرّف المنتج أو النسخة غير صالح');return {product_id:product,variant_id:variant};}
function product(b){const k=key(b.product_id,b.variant_id);if(!Array.isArray(b.components)||!b.components.length||b.components.length>6||b.components.some(x=>!TAGS.has(x)))throw fail(400,'اختر محتويات المنتج أو البكج');let url=null;if(b.product_url){try{const u=new URL(b.product_url);if(u.protocol!=='https:'||!['linkstore-sa.com','www.linkstore-sa.com','mtjr.at'].includes(u.hostname)||u.username||u.password||u.port||u.hash||u.href.length>1000)throw Error();url=u.href;}catch{throw fail(400,'أدخل رابط HTTPS لمنتج متجرك');}}return {...k,name:text(b.name,150),model:text(b.model,100),components:[...new Set(b.components)],product_url:url,updated_at:new Date().toISOString()};}
function settings(b){if(b.mode&&b.mode!=='preview'||b.enabled===true)throw fail(400,'هذه المرحلة للمعاينة؛ الإرسال لم يجهّز بعد');for(const [k,min,max]of [['delay_days',1,30],['batch_limit',1,10],['cooldown_days',7,90],['stock_api_budget',0,1000]])if(!Number.isInteger(b[k])||b[k]<min||b[k]>max)throw fail(400,'إعدادات الجدولة غير صالحة');if(!Array.isArray(b.batch_hours)||b.batch_hours.length<1||b.batch_hours.length>4||b.batch_hours.some(h=>!Number.isInteger(h)||h<0||h>23))throw fail(400,'مواعيد الدفعات غير صالحة');return {mode:'preview',delay_days:b.delay_days,batch_limit:b.batch_limit,cooldown_days:b.cooldown_days,stock_api_budget:b.stock_api_budget,batch_hours:[...new Set(b.batch_hours)].sort((a,b)=>a-b),updated_at:new Date().toISOString()};}
async function admin(req,res){const filter=`merchant_id=eq.${MERCHANT_ID}`;
 if(req.method==='GET'){
  try{const [s,products,rules,catalog,preview]=await Promise.all([sb(`crm_postpurchase_settings?${filter}&select=*`),sb(`crm_postpurchase_products?${filter}&select=*&order=name.asc&limit=500`),sb(`crm_postpurchase_rules?${filter}&select=*&order=created_at.desc&limit=200`),sb('rpc/crm_postpurchase_catalog',{method:'POST',body:JSON.stringify({p_merchant_id:MERCHANT_ID})}),sb('rpc/crm_postpurchase_preview',{method:'POST',body:JSON.stringify({p_merchant_id:MERCHANT_ID})})]);return json(res,200,{ok:true,ready:true,settings:s[0],products,rules,catalog,preview,automatic:await require('./postpurchase-auto').load()});}
  catch(e){if(['42P01','PGRST205','PGRST202','42883'].includes(e.code)||/"code":"(?:42P01|PGRST205|PGRST202|42883)"/.test(e.message||''))return json(res,200,{ok:true,ready:false});throw e;}
 }
 const b=bodyObject(req);
 if(req.method==='POST'&&b.action==='analyze'){
  try{return json(res,200,{ok:true,...await require('./postpurchase-auto').analyze()});}
  catch(e){if(e.postpurchaseSafe)return json(res,503,{ok:false,error:e.message,stage:e.analysisStage,code:e.analysisCode,salla_requests:0});throw e;}
 }
 if(req.method==='POST'&&b.action==='import'){try{return json(res,200,{ok:true,...await require('./postpurchase-auto').importPage({refresh:b.refresh===true})});}catch(e){if(e.postpurchaseSafe)return json(res,503,{ok:false,error:e.message});throw e;}}
 if(req.method==='PUT'&&b.action==='settings'){await sb(`crm_postpurchase_settings?${filter}`,{method:'PATCH',body:JSON.stringify(settings(b))});return json(res,200,{ok:true});}
 if(req.method==='PUT'&&b.action==='product'){const p=product(b);await sb('crm_postpurchase_products?on_conflict=merchant_id,product_id,variant_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates'},body:JSON.stringify({merchant_id:MERCHANT_ID,...p,origin:'manual'})});await require('./postpurchase-auto').analyze();return json(res,200,{ok:true});}
 if(req.method==='POST'&&b.action==='rule'){const t=key(b.trigger_product_id,b.trigger_variant_id),f=key(b.offer_product_id,b.offer_variant_id);if(t.product_id===f.product_id&&t.variant_id===f.variant_id)throw fail(400,'العرض يجب أن يكون منتجًا مكملًا');const all=await sb(`crm_postpurchase_products?${filter}&select=product_id,variant_id,model`);const get=k=>all.find(x=>x.product_id===k.product_id&&x.variant_id===k.variant_id);if(!get(t)||!get(f)||get(t).model!==get(f).model)throw fail(400,'عرّف المنتجين لنفس موديل الجهاز أولًا');await sb('crm_postpurchase_rules',{method:'POST',body:JSON.stringify({merchant_id:MERCHANT_ID,name:text(b.name,120),trigger_product_id:t.product_id,trigger_variant_id:t.variant_id,offer_product_id:f.product_id,offer_variant_id:f.variant_id,active:true})});return json(res,201,{ok:true});}
 if(req.method==='PATCH'&&b.action==='rule'){if(!UUID.test(b.id)||typeof b.active!=='boolean')throw fail(400,'قاعدة غير صالحة');await sb(`crm_postpurchase_rules?${filter}&id=eq.${b.id}`,{method:'PATCH',body:JSON.stringify({active:b.active,paused_by_user:!b.active})});return json(res,200,{ok:true});}
 return json(res,405,{ok:false,error:'Method not allowed'});
}
module.exports={admin,product,settings,key};

