const {sb,MERCHANT_ID,fail,decryptCredentials}=require('./crm');
const {losslessJSON,nextPage}=require('./salla-sync');
const safeFail=message=>Object.assign(fail(503,message),{postpurchaseSafe:true});
const ID=/^[0-9]{1,20}$/;
function identifier(v){if(typeof v==='number'&&!Number.isSafeInteger(v))throw fail(400,'معرّف منتج غير دقيق');const id=String(v??'');if(!ID.test(id))throw fail(400,'معرّف منتج غير صالح');return id;}
function norm(v){return String(v??'').replace(/[٠-٩]/g,c=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(c))).replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<[^>]*>/g,' ').replace(/&(?:nbsp|amp);/gi,' ').replace(/[\u064b-\u065f\u0670ـ]/g,'').replace(/[إأآ]/g,'ا').toLowerCase().replace(/pro\s*max/g,'pro max').replace(/برو\s*ماكس/g,'pro max').replace(/برو/g,'pro').replace(/ماكس/g,'max').replace(/الترا|ألترا/g,'ultra').replace(/بلس/g,'plus').replace(/ايفون|اي فون|آيفون/g,'iphone').replace(/سامسونج/g,'samsung').replace(/\s+/g,' ').trim();}
function models(v){const s=norm(v),out=new Set();for(const m of s.matchAll(/(?:iphone\s*)(1[1-9]|20)(?:\s*(pro\s*max|pro|max|plus|mini|air))?(?!\d)/g))out.add('iPhone '+m[1]+(m[2]?' '+m[2].split(' ').map(x=>x[0].toUpperCase()+x.slice(1)).join(' '):''));for(const m of s.matchAll(/(?:samsung\s*|galaxy\s*)?\bs\s*(2[0-9]|30)(?:\s*(ultra|plus|fe)|\s*(\+))?(?!\d)/g))out.add('Samsung S'+m[1]+(m[2]?' '+m[2].toUpperCase():(m[3]?' Plus':'')));return [...out];}
function components(v){const s=norm(v),tags=[];if(/كفر|جراب|\bcase\b|\bcover\b/.test(s))tags.push('case');if(/حماية\s*(?:لل)?شاش|استيكر|ستيكر|screen\s*(?:protector|protection)|privacy\s*(?:glass|screen)/.test(s))tags.push('screen');if(/عدسات|عدسة|\blens(?:es)?\b/.test(s))tags.push('lens');if(/(?:اطار|فريم)\s*(?:للكاميرا|الكاميرا|كاميرا|الكاميرات)|camera\s*frame/.test(s))tags.push('camera_frame');return tags;}
function safeUrl(v){try{const u=new URL(v);return u.protocol==='https:'&&['linkstore-sa.com','www.linkstore-sa.com','mtjr.at'].includes(u.hostname)&&!u.username&&!u.password&&!u.port&&!u.hash&&u.href.length<=1000?u.href:null;}catch{return null;}}
function sanitize(p){return {id:identifier(p.id),name:String(p.name||'').slice(0,150),description:String(p.description||'').slice(0,6000),product_url:safeUrl(p.urls?.customer||p.product_url),status:String(p.status||''),is_available:typeof p.is_available==='boolean'?p.is_available:null,quantity:p.quantity!=null&&Number.isFinite(Number(p.quantity))&&Number(p.quantity)>=0?Number(p.quantity):null,unlimited_quantity:p.unlimited_quantity===true,options:Array.isArray(p.options)?p.options.slice(0,20).map(x=>({name:String(x.name||'').slice(0,100),values:(Array.isArray(x.values)?x.values:[]).slice(0,100).map(v=>({id:identifier(v.id),name:String(v.name||'').slice(0,100)}))})):[],has_skus:Array.isArray(p.skus)&&p.skus.length>1&&!(Array.isArray(p.options)&&p.options.length),source:'salla_catalog'};}
function infer(p){const product_id=identifier(p.id||p.product_id),name=String(p.name||'').slice(0,150),title=norm(name),titleModels=models(name),descModels=models(p.description),tags=components(name);let componentList=tags,modelList=titleModels.length?titleModels:descModels;const reasons=[];
 const excluded=(!modelList.length&&!tags.length&&/حامل|شاحن|كيبل|باور|power bank|charger|car mount/.test(title))||/تغليف|اشتراك|تركيب|خدمة|\bservice\b/.test(title)||/^(hidden|out|deleted|draft)$/.test(p.status||'');
 if(excluded)return {product_id,variant_id:'',name,decision:'excluded',reasons:['excluded_product'],profile:{}};
 if(p.source!=='salla_catalog')reasons.push('catalog_required');
 if(/pro\b.*(?:و|\/|او|&|and).*max/.test(title)||/iphone\s*1[1-9]\s*(?:و|\/|او|&|and)\s*1[1-9]/.test(title))reasons.push('multiple_models');
 if(modelList.length!==1)reasons.push(modelList.length?'multiple_models':'model_unknown');
 if(titleModels.length&&descModels.some(m=>!titleModels.includes(m)))reasons.push('model_conflict');
 const modelOptions=(p.options||[]).some(x=>/موديل|model|مقاس|size|نوع.*(?:جهاز|جوال)|هاتف|phone/.test(norm(x.name))||x.values?.some(v=>models(v.name).length));
 if(modelOptions||p.has_skus||(p.options||[]).some(x=>!/لون|color|الخامة|مادة|material/.test(norm(x.name))))reasons.push('variants_review');
 if(!tags.length){componentList=components(p.description);reasons.push('type_unknown');}
 if(/بكج|باقة|\bpack(?:age)?\b|\bbundle\b|حماية متكاملة/.test(title)||tags.length>1){componentList=[...new Set([...tags,...components(p.description)])];reasons.push('bundle_contents_review');}
 const url=safeUrl(p.product_url||p.urls?.customer);if(!url)reasons.push('url_missing');
 if(!name)reasons.push('name_missing');
 return {product_id,variant_id:'',name:name||product_id,decision:reasons.length?'review':'auto',reasons,profile:{product_id,variant_id:'',name:name||product_id,model:modelList.length===1?modelList[0]:'',components:componentList,product_url:url}};
}
async function load(database=sb){try{const [importRows,usage,suggestions]=await Promise.all([database(`crm_postpurchase_import?merchant_id=eq.${MERCHANT_ID}&select=next_page,completed,completed_at,last_error,updated_at`),database(`crm_postpurchase_api_usage?merchant_id=eq.${MERCHANT_ID}&select=month,requests&order=month.desc&limit=1`),database(`crm_postpurchase_suggestions?merchant_id=eq.${MERCHANT_ID}&select=product_id,variant_id,name,decision,reasons,suggestion&order=decision.desc,name.asc&limit=1500`)]);const month=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Riyadh',year:'numeric',month:'2-digit'}).format(new Date());const used=String(usage[0]?.month||'').startsWith(month)?usage[0].requests:0;return {ready:true,import:importRows[0]||null,requests:used,budget:20,suggestions};}catch(e){if(/PGRST205|42P01/.test(e.message||''))return {ready:false};throw e;}}
async function analyze(database=sb){const [run]=await database(`crm_postpurchase_import?merchant_id=eq.${MERCHANT_ID}&select=completed`);if(run&&!run.completed)return {deferred:true,reason:'catalog_incomplete',salla_requests:0};let cached=[];for(let offset=0;offset<1500;offset+=500){const rows=await database(`crm_postpurchase_catalog_cache?merchant_id=eq.${MERCHANT_ID}&select=product&order=product_id.asc&limit=500&offset=${offset}`);cached.push(...rows);if(rows.length<500)break;}let source=cached.map(x=>x.product);if(!source.length){const local=await database('rpc/crm_postpurchase_catalog',{method:'POST',body:JSON.stringify({p_merchant_id:MERCHANT_ID})});source=local.map(x=>({...x,source:'local_orders'}));}
 const suggestions=source.map(infer);return database('rpc/crm_pp_apply_suggestions',{method:'POST',body:JSON.stringify({p_merchant_id:MERCHANT_ID,p_suggestions:suggestions})});}
async function importPage({database=sb,request=fetch,refresh=false,credentials}={}){
 // Validate authorization locally before reserving an external request.
 let tokens;if(credentials)tokens=await credentials();else{const [c]=await database(`crm_connections?merchant_id=eq.${MERCHANT_ID}&provider=eq.salla&select=status,credentials_encrypted,token_expires_at`);if(c?.status!=='connected'||!c.credentials_encrypted||c.token_expires_at&&Date.parse(c.token_expires_at)<=Date.now())throw safeFail('تفويض سلة غير متصل أو منتهي');tokens=decryptCredentials(c.credentials_encrypted);}if(!tokens?.access_token)throw safeFail('تفويض سلة غير صالح');
 const claim=await database('rpc/crm_pp_reserve_import',{method:'POST',body:JSON.stringify({p_merchant_id:MERCHANT_ID,p_refresh:refresh})});if(claim.idle)return {done:true,reason:claim.idle,requests:0};
 const finish=async(products,done,error=null)=>{const ok=await database('rpc/crm_pp_finish_import',{method:'POST',body:JSON.stringify({p_merchant_id:MERCHANT_ID,p_token:claim.token,p_page:claim.page,p_products:products,p_done:done,p_error:error})});if(ok!==true)throw safeFail('تعذر حفظ صفحة الكتالوج؛ توقف الجلب');};
 let response,data;try{response=await request(`https://api.salla.dev/admin/v2/products?page=${claim.page}&per_page=60`,{headers:{Authorization:`Bearer ${tokens.access_token}`,Accept:'application/json'},redirect:'error',signal:AbortSignal.timeout(12000)});if(!response.ok){await finish([],false,'HTTP '+response.status);throw safeFail(`تعذر جلب الكتالوج من سلة (HTTP ${response.status})؛ توقف الجلب بدون إعادة تلقائية`);}data=losslessJSON(await response.text());if(data.success===false||!Array.isArray(data.data)||data.data.length>60)throw Error('Invalid response');}
 catch(e){if(e.statusCode)throw e;await finish([],false,'connection_or_response_error');throw safeFail('تعذر قراءة صفحة الكتالوج؛ توقف الجلب بدون إعادة تلقائية');}
 let products;try{products=data.data.map(sanitize);}catch{await finish([],false,'invalid_product');throw safeFail('بيانات منتج غير صالحة؛ توقف الجلب');}
 const next=nextPage(data.pagination,claim.page,products.length);await finish(products,!next);return {done:!next,page:claim.page,saved:products.length,requests:claim.requests,budget:20};
}
module.exports={infer,models,components,sanitize,load,analyze,importPage};
